version: "2.1"

services:
   mysql:
     image: mysql:5.6
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: PM-DBPassw0rd
     networks:
     - pm-net

   processmaker:
     depends_on:
     - mysql
     image: processmaker/processmaker
     ports:
       - "80:80"
     restart: always
     environment:
       URL: "127.0.0.1"
     networks:
      - pm-net

networks:
  pm-net:
    driver: bridge
    ipam:
      driver: default
      config:
      -
        subnet: 172.16.150.0/24
